- name: Info message
  ansible.builtin.debug:
    msg: "Using Debian install"

- name: Copy Debian package to target host
  ansible.builtin.copy:
    src: "{{ tenzir_debian_package }}"
    dest: /tmp/tenzir.deb
    mode: '0640'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Install Tenzir Debian package
  ansible.builtin.apt:
    deb: /tmp/tenzir.deb
    allow_downgrade: yes
