# This file contains the configuration for GitHub Label Sync.
#
# Usage:
#
#    github-label-sync --access-token TOKEN --labels labels.yaml REPO
#
# Where TOKEN is a GitHub Access Token and REPO the repository name to apply
# this configuration file to, e.g., tenzir/tenzir.
#
# For details, see:
# https://github.com/Financial-Times/github-label-sync

# Status
- name: blocked
  color: dddddd
  description: Blocked by an (external) issue
# Type of work
- name: bug
  color: fbca04
  description: Incorrect behavior
- name: feature
  color: fbca04
  description: New functionality
- name: improvement
  color: fbca04
  description: An incremental enhancement of an existing feature
- name: maintenance
  color: fbca04
  description: Tasks for keeping up the infrastructure
- name: performance
  color: fbca04
  description: Improvements or regressions of performance
- name: refactoring
  color: fbca04
  description: Restructuring of existing code
# Code base part
- name: ci
  color: 0366d6
  description: Continuous integration and delivery
- name: dependencies
  color: 0366d6
  description: Update of dependent software
- name: docs
  color: 0366d6
  description: Documentation and blog
- name: packaging
  color: 0366d6
  description: Relating to the build scaffold
- name: rfc
  color: 0366d6
  description: A Request For Comments (RFC)
# Functionality
- name: app
  color: d93f0b
  description: Our app at app.tenzir.com
- name: platform
  color: d93f0b
  description: The infra behind app.tenzir.com
- name: engine
  color: d93f0b
  description: Core pipeline and storage engine
- name: connector
  color: d93f0b
  description: Loader and saver
- name: format
  color: d93f0b
  description: Parser and printer
- name: operator
  color: d93f0b
  description: Source, transformation, and sink
- name: language
  color: d93f0b
  description: Tenzir Query Language (TQL)
- name: integration
  color: d93f0b
  description: Integration with third-party tools
