default: false

# Tags
html: false
indentation: false
links: false
spelling: true
whitespace: true

# MD010/no-hard-tabs - Hard tabs
MD010:
  code_blocks: false

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: false
