version: '3'
services:
  matcher_client:
    image: tenzir/tenzircloud:matcher
    build:
      context: ../../resources
      dockerfile: ../docker/matcher/matcher_client.Dockerfile
      args:
        - TENZIR_IMAGE
        - TENZIR_VERSION
