blank_issues_enabled: false
contact_links:
  - name: Usage Question
    url: https://github.com/tenzir/tenzir/discussions/new?category=q-a
    about: Just want to ask a question? Go on
  - name: Tenzir Community Chat
    url: https://docs.tenzir.com/discord
    about: Chat with us on Discord
  - name: Tenzir Documentation
    url: https://docs.tenzir.com
    about: Read up on Tenzir
