version: '3'
services:
  misp:
    image: tenzir/vastcloud:misp
    build:
      context: ../../../../docker/misp/
      args:
        - MISP_VERSION=${TENZIR_MISP_VERSION}
  misp_proxy:
    image: tenzir/vastcloud:misp_proxy
    build:
      context: ../../../../docker/misp/proxy
