version: '3'
services:
  tenzir_server:
    image: tenzir/tenzircloud:server
    build:
      context: ../../resources
      dockerfile: ../docker/core-2/server.Dockerfile
      args:
        - TENZIR_IMAGE
        - TENZIR_VERSION
  lambda_client:
    image: tenzir/tenzircloud:lambda_client
    build:
      context: ../../resources
      dockerfile: ../docker/core-2/lambda_client.Dockerfile
      args:
        - TENZIR_IMAGE
        - TENZIR_VERSION
