version: "3"
services:
  quarto:
    volumes:
      - ../..:/mnt/host
      - quarto:/home/tenzir/.cache
    environment:
      - HOST_UID
      - HOST_GID
    privileged: true
    build:
      target: quarto-bind

volumes:
  quarto:
    driver: local
