version: "3"
services:
  quarto:
    pull_policy: build
    image: ${TENZIR_CONTAINER_REGISTRY:-docker.io}/tenzir/tenzir-quarto:${TENZIR_CONTAINER_REF:-latest}
    build:
      context: ../..
      dockerfile: docker/quarto/Dockerfile
      args:
        - TENZIR_VERSION=${TENZIR_CONTAINER_REF:-latest}
        - TENZIR_CONTAINER_REGISTRY=${TENZIR_CONTAINER_REGISTRY:-docker.io}
        - QUARTO_VERSION=${QUARTO_VERSION:-1.1.251}
