version: "3.8"
services:
  neuron:
    network_mode: "container:tenzir-server"  # used for tests only
    depends_on:
      - tenzir

  cortex:
    environment:
      - CORTEX_NEURON_NETWORK_MODE=container:tenzir-server
    depends_on:
      - tenzir

  thehive:
    environment:
      - TENZIR_ENDPOINT=tenzir:5158
