name: Manual
on:
  workflow_dispatch:
    inputs:
      push-de-to-ghcr:
        type: boolean
        default: false
        required: false
      push-ce-to-ecr:
        type: boolean
        default: false
        required: false
      push-ee-to-ecr:
        type: boolean
        default: false
        required: false
      tag:
        type: string
        required: false
      tag-sha:
        type: boolean
        required: false
        default: false

jobs:
  configure:
    name: Configure Inputs
    runs-on: ubuntu-20.04
    outputs:
      docker-config: ${{ steps.docker.outputs.docker-config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch Tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Calculate Version
        id: version
        run: |
          version="$(git describe --abbrev=10 --long --dirty --match='v[0-9]*')"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
      - name: Configure Docker
        id: docker
        run: |
          tags=()
          if [[ '${{ inputs.tag }}' != "" ]]; then
            tags+=('${{ inputs.tag }}')
          fi
          if [[ '${{ inputs.tag-sha }}' == 'true' ]]; then
            tags+=('${{ github.sha }}')
          fi
          if [[ '${{ inputs.build }}' == 'true' ]]; then
            tags+=('${{ github.sha }}')
          fi
          docker_config="$(jq -nc \
            '."editions" = [
              if ${{ inputs.push-de-to-ghcr }} then
                {
                  "name": "vast-de", "target": "production", "registries": [
                   "ghcr.io"
                  ]
                }
              else
                empty
              end,
              if ${{ inputs.push-ce-to-ecr }} then
                {
                  "name": "vast-ce", "target": "vast-ce", "registries": [
                   "622024652768.dkr.ecr.eu-west-1.amazonaws.com"
                  ]
                }
              else
                empty
              end,
              if ${{ inputs.push-ee-to-ecr }} then
                {
                  "name": "vast-ee", "target": "vast-ee", "registries": [
                   "622024652768.dkr.ecr.eu-west-1.amazonaws.com"
                  ]
                }
              else
                empty
              end
            ] | ."version" = $v | ."tags" = $ARGS.positional' \
            --arg v "${{ steps.version.outputs.version }}" \
            --args -- "${tags[@]}")"
          echo "docker-config=${docker_config}" >> "$GITHUB_OUTPUT"
          echo "::notice docker-config = ${docker_config}"

  docker-vast:
    name: Docker
    needs:
      - configure
    uses: ./.github/workflows/docker.yaml
    with:
      config: ${{ needs.configure.outputs.docker-config }}
    secrets: inherit
