name: Nix
on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build:
    name: Build & Install
    runs-on: ${{ fromJSON(inputs.config).editions[0].gha-runner-labels }}
    steps:
      - name: Prevent pushing protected editions to public repos
        run: |
          # Create 'name registry' pairs
          jq -r '.editions[] | select(."image-registries" | length > 0) | .name as $name | ."image-registries"[]? // ."image-registries" | [ $name, . ] | join(" ")' \
            <<< '${{ inputs.config }}' | while read -r name registry; do
            # Explicitly allow blessed images.
            [[ "${name}" =~ ^tenzir$ ]] && continue
            # Explicitly allow private registries.
            [[ "${registry}" == "622024652768.dkr.ecr.eu-west-1.amazonaws.com" ]] && continue
            echo "::error Pushing ${name} to ${registry} is forbidden"
            exit 1
          done
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        id: cfg
        run: |
          # Configure
          echo '::notice triggered by: ${{ github.event_name }}'
          echo '::notice inputs = ${{ toJSON(fromJSON(inputs.config)) }}'
          echo "::notice checking registries..."
          echo "needs-docker-hub=false" >> "$GITHUB_OUTPUT"
          echo "needs-ghcr=false" >> "$GITHUB_OUTPUT"
          echo "needs-ecr=false" >> "$GITHUB_OUTPUT"
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            jq -r '.editions | map( ."image-registries"[]) | unique | .[]
                   | if . == "docker.io" then
                       "needs-docker-hub=true"
                     elif . == "ghcr.io" then
                       "needs-ghcr=true"
                     elif . == "622024652768.dkr.ecr.eu-west-1.amazonaws.com" then
                       "needs-ecr=true"
                     else
                       empty
                     end
                   | @text' \
                   <<< '${{ inputs.config }}' >> "${GITHUB_OUTPUT}"
          fi
          echo "::notice checking tenzir-plugins..."
          jq -r '@text "upload-to-github=\(.editions | any(."upload-package-to-github"))"' \
                   <<< '${{ inputs.config }}' >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
      - name: Check outputs
        run: |
          echo 'cfg outputs: ${{ toJSON(steps.cfg.outputs) }}'
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TENZIR_PLUGINS_DEPLOY_KEY }}
      - name: Login to GitHub Container Registry
        if: steps.cfg.outputs.needs-ghcr == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tenzir-bot
          password: ${{ secrets.TENZIR_BOT_GITHUB_TOKEN }}
      - name: Login to Docker Hub
        if: steps.cfg.outputs.needs-docker-hub == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Configure AWS Credentials
        if: steps.cfg.outputs.needs-ecr == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::622024652768:role/ecr-tenzir-ce-github-access
          aws-region: eu-west-1
      - name: Login to AWS ECR
        if: steps.cfg.outputs.needs-ecr == 'true'
        uses: aws-actions/amazon-ecr-login@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
        with:
          # disables telemetry
          diagnostic-endpoint: ""
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: tenzir
          authToken: "${{ secrets.CACHIX_TENZIR_API_TOKEN }}"
          # Avoid pushing the full enterprise edition.
          pushFilter: "tenzir-ee"
      - name: Build Nix Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GCS_SERVICE_ACCOUNT_CREDENTIALS }}
          RCLONE_GCS_BUCKET_POLICY_ONLY: True
        run: |
          nix shell --inputs-from ./. \
            nixpkgs#git \
            nixpkgs#nushellFull \
            nixpkgs#rclone \
            nixpkgs#skopeo \
            -c .github/workflows/nix.nu '${{ inputs.config }}'
      - name: Upload Tarball to Github
        if: >-
          runner.os == 'Linux' &&
          steps.cfg.outputs.upload-to-github == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: "./packages/tarball/*.tar.gz"
          if-no-files-found: error
      - name: Upload Debian Package to Github
        if: >-
          runner.os == 'Linux' &&
          steps.cfg.outputs.upload-to-github == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: debian
          path: "./packages/debian/*.deb"
          if-no-files-found: error
      - name: Upload macOS Package to Github
        if: >-
          runner.os == 'macOS' &&
          steps.cfg.outputs.upload-to-github == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: "./packages/macOS/*.pkg"
          if-no-files-found: error
      - name: Test Installation
        if: runner.os == 'Linux'
        run: |
          deb_file="$(basename ./packages/debian/tenzir*.deb)"
          docker build docker/systemd-test -t installer-test
          docker run -d --name installer-test \
                 --privileged \
                 --volume=.:/src/tenzir:ro \
                 --volume="./packages/debian":/tmp/packages:ro \
                 --volume=/sys/fs/cgroup:/sys/fs/cgroup:rw \
                 --cgroupns=host \
                 installer-test
          # TODO: Ideally we would have some way to block until systemd is fully
          # booted, but sleeping a bit works almost every time.
          sleep 5
          docker exec -e TENZIR_PACKAGE_URL="file:///tmp/packages/${deb_file}" installer-test bash -c \
                 "/src/tenzir/scripts/install.sh"
          docker exec installer-test halt
