name: "Style Check"
on:
  pull_request:
    types:
      - opened
      - synchronize
  merge_group:
    types:
      - checks_requested

env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clang Format
        run: |
          pip install --upgrade clang-format
          which clang-format
          clang-format --version
          git diff -U0 --no-color $(git merge-base origin/main HEAD) -- \
              '*.cpp' '*.cpp.in' '*.hpp' '*.hpp.in' |
            scripts/clang-format-diff.py -p1

      - name: CMake Format
        run: |
          pip install --upgrade cmake_format
          git diff --name-only --no-color --diff-filter=ACM $(git merge-base origin/main HEAD) -- "**CMakeLists.txt" "**.cmake" |
            tr '\\n' '\\0'
            xargs -0 cmake-format --in-place
          git diff --exit-code

      - name: Black
        run: |
          pip install --upgrade black
          # Note: black fails when it doesn't have to do anything.
          git diff --name-only --no-color --diff-filter=ACM $(git merge-base origin/main HEAD) |
            tr '\\n' '\\0' |
            grep '\.py$' |
            xargs -0 --no-run-if-empty black || true
          git diff --exit-code

      - name: ShellCheck
        run: |
          git diff --name-only --no-color --diff-filter=ACM $(git merge-base origin/master HEAD) |
            scripts/shellcheck.bash

      - name: yamllint
        run: |
          pip install --upgrade yamllint
          git ls-files -z '*.yaml' '.yml' | xargs -0 yamllint

      - name: Ansible Lint
        run: |
          pip install --upgrade ansible ansible-lint
          ansible-galaxy collection install ansible.posix
          ansible-lint --strict --profile production ansible

      - name: Terraform fmt
        run: |
          terraform fmt -check -recursive -diff

      - name: Markdown Lint
        run: |
          npm install --no-save markdownlint-cli
          npx markdownlint --ignore libtenzir/aux --ignore node_modules .
